/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Camera } from 'react-feather'

function IconCamera(props: any) {
  return <IconBase icon={Camera} {...props} />
}

export default IconCamera
