/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { ExternalLink } from 'react-feather'
import IconBase from './../../IconBase'

function IconExternalLink(props: any) {
  return <IconBase icon={ExternalLink} {...props} />
}

export default IconExternalLink
