/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { CornerRightUp } from 'react-feather'

function IconCornerRightUp(props: any) {
  return <IconBase icon={CornerRightUp} {...props} />
}

export default IconCornerRightUp
