/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Bell } from 'react-feather'

function IconBell(props: any) {
  return <IconBase icon={Bell} {...props} />
}

export default IconBell
