/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { BellOff } from 'react-feather'

function IconBellOff(props: any) {
  return <IconBase icon={BellOff} {...props} />
}

export default IconBellOff
