/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { UploadCloud } from 'react-feather'
import IconBase from './../../IconBase'

function IconUploadCloud(props: any) {
  return <IconBase icon={UploadCloud} {...props} />
}

export default IconUploadCloud
