/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { AlignCenter } from 'react-feather'

function IconAlignCenter(props: any) {
  return <IconBase icon={AlignCenter} {...props} />
}

export default IconAlignCenter
