/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { ArrowRight } from 'react-feather'
import IconBase from './../../IconBase'

function IconArrowRight(props: any) {
  return <IconBase icon={ArrowRight} {...props} />
}

export default IconArrowRight
