/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { ArrowRight } from 'react-feather'

function IconArrowRight(props: any) {
  return <IconBase icon={ArrowRight} {...props} />
}

export default IconArrowRight
