/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Coffee } from 'react-feather'

function IconCoffee(props: any) {
  return <IconBase icon={Coffee} {...props} />
}

export default IconCoffee
