/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Tablet } from 'react-feather'
import IconBase from './../../IconBase'

function IconTablet(props: any) {
  return <IconBase icon={Tablet} {...props} />
}

export default IconTablet
