/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { BookOpen } from 'react-feather'
import IconBase from './../../IconBase'

function IconBookOpen(props: any) {
  return <IconBase icon={BookOpen} {...props} />
}

export default IconBookOpen
