/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Truck } from 'react-feather'

function IconTruck(props: any) {
  return <IconBase icon={Truck} {...props} />
}

export default IconTruck
