/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Smile } from 'react-feather'
import IconBase from './../../IconBase'

function IconSmile(props: any) {
  return <IconBase icon={Smile} {...props} />
}

export default IconSmile
