/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { CheckCircle } from 'react-feather'
import IconBase from './../../IconBase'

function IconCheckCircle(props: any) {
  return <IconBase icon={CheckCircle} {...props} />
}

export default IconCheckCircle
