/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { AlertCircle } from 'react-feather'

function IconAlertCircle(props: any) {
  return <IconBase icon={AlertCircle} {...props} />
}

export default IconAlertCircle
