/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Shield } from 'react-feather'

function IconShield(props: any) {
  return <IconBase icon={Shield} {...props} />
}

export default IconShield
