/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Globe } from 'react-feather'

function IconGlobe(props: any) {
  return <IconBase icon={Globe} {...props} />
}

export default IconGlobe
