/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { CornerDownLeft } from 'react-feather'

function IconCornerDownLeft(props: any) {
  return <IconBase icon={CornerDownLeft} {...props} />
}

export default IconCornerDownLeft
