/**
* This file is generated by @wesbitty automatically
* Do Not Edit
*/

import React from 'react'
// @ts-ignore
import Icon from 'react-feather/dist/icons/bar-chart'
import IconBase from './../../IconBase'

function IconBarChart(props: any) {
  return <IconBase icon={Icon} {...props} />
}

export default IconBarChart
  