/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Database } from 'react-feather'

function IconDatabase(props: any) {
  return <IconBase icon={Database} {...props} />
}

export default IconDatabase
