// DO NOT EDIT
  // This file is generated by IconGenerator script
  import React from 'react'
  // @ts-ignore
  import Icon from 'react-feather/dist/icons/bar-chart-2'
  import IconBase from '../../IconBase'

  function IconBarChart2(props: any) {
    return <IconBase icon={Icon} {...props} />
  }

  export default IconBarChart2
  