/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { BarChart2 } from 'react-feather'

function IconBarChart2(props: any) {
  return <IconBase icon={BarChart2} {...props} />
}

export default IconBarChart2
