/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Download } from 'react-feather'

function IconDownload(props: any) {
  return <IconBase icon={Download} {...props} />
}

export default IconDownload
