/**
* This file is generated by @wesbitty automatically
* Do Not Edit
*/
declare function IconArrowLeftCircle(props: any): import("react/jsx-runtime").JSX.Element;
export default IconArrowLeftCircle;
