/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Pause } from 'react-feather'

function IconPause(props: any) {
  return <IconBase icon={Pause} {...props} />
}

export default IconPause
