[[plugins]]
  package = "@netlify/plugin-nextjs"

[build]
command = "npm run build"
publish = "apps/web/.next"

[template.environment]
NEXTAUTH_SECRET = "Secret, use https://generate-secret.now.sh/32 to create one."
DATABASE_URL = "Database URL, leave blank for now. See docs for more info."
NEXTAUTH_URL = "NextAuth URL, leave blank for now. See docs for more info."
GITHUB_ID= "Github ID"
GITHUB_SECRET= "Github secret"