[[plugins]]
  package = "@netlify/plugin-nextjs"

[build]
command = "npm run build"
publish = "apps/web/.next"
ignore = "if [ $CACHED_COMMIT_REF == $COMMIT_REF ]; then (exit 1); else git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ../..; fi;"