/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Airplay } from 'react-feather'
import IconBase from './../../IconBase'

function IconAirplay(props: any) {
  return <IconBase icon={Airplay} {...props} />
}

export default IconAirplay
