/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Chrome } from 'react-feather'

function IconChrome(props: any) {
  return <IconBase icon={Chrome} {...props} />
}

export default IconChrome
