/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Octagon } from 'react-feather'

function IconOctagon(props: any) {
  return <IconBase icon={Octagon} {...props} />
}

export default IconOctagon
