/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Terminal } from 'react-feather'

function IconTerminal(props: any) {
  return <IconBase icon={Terminal} {...props} />
}

export default IconTerminal
