/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Send } from 'react-feather'

function IconSend(props: any) {
  return <IconBase icon={Send} {...props} />
}

export default IconSend
