/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Battery } from 'react-feather'

function IconBattery(props: any) {
  return <IconBase icon={Battery} {...props} />
}

export default IconBattery
