/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { GitPullRequest } from 'react-feather'

function IconGitPullRequest(props: any) {
  return <IconBase icon={GitPullRequest} {...props} />
}

export default IconGitPullRequest
