/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { CornerDownRight } from 'react-feather'
import IconBase from './../../IconBase'

function IconCornerDownRight(props: any) {
  return <IconBase icon={CornerDownRight} {...props} />
}

export default IconCornerDownRight
