/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { ArrowDownCircle } from 'react-feather'

function IconArrowDownCircle(props: any) {
  return <IconBase icon={ArrowDownCircle} {...props} />
}

export default IconArrowDownCircle
