/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Minimize2 } from 'react-feather'

function IconMinimize2(props: any) {
  return <IconBase icon={Minimize2} {...props} />
}

export default IconMinimize2
