/**
* This file is generated by @wesbitty automatically
* Do Not Edit
*/
declare function IconAlignJustify(props: any): import("react/jsx-runtime").JSX.Element;
export default IconAlignJustify;
