/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Radio } from 'react-feather'
import IconBase from './../../IconBase'

function IconRadio(props: any) {
  return <IconBase icon={Radio} {...props} />
}

export default IconRadio
