/**
* This file is generated by @wesbitty automatically
* Do Not Edit
*/

import React from 'react'
// @ts-ignore
import Icon from 'react-feather/dist/icons/archive'
import IconBase from './../../IconBase'

function IconArchive(props: any) {
  return <IconBase icon={Icon} {...props} />
}

export default IconArchive
  