/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Archive } from 'react-feather'
import IconBase from './../../IconBase'

function IconArchive(props: any) {
  return <IconBase icon={Archive} {...props} />
}

export default IconArchive
