/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Hash } from 'react-feather'

function IconHash(props: any) {
  return <IconBase icon={Hash} {...props} />
}

export default IconHash
