/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { AtSign } from 'react-feather'
import IconBase from './../../IconBase'

function IconAtSign(props: any) {
  return <IconBase icon={AtSign} {...props} />
}

export default IconAtSign
