/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { AtSign } from 'react-feather'

function IconAtSign(props: any) {
  return <IconBase icon={AtSign} {...props} />
}

export default IconAtSign
