# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Script Task
    init: cd ../../home/gitpod/.config && mkdir planetscale && cd ../../../workspace/wesbitty
    command: |
      brew install planetscale/tap/pscale
      brew install mysql-client
      npm install -g vercel
  - name: Install Deps
  - init: |
      npm install
      pnpm build
    command: cd apps/web && pnpm start
