version: '3'

services:
  www:
    container_name: www
    build:
      context: .
      dockerfile: ./apps/www/Dockerfile
    restart: always
    ports:
      - 8080:8080
    networks:
      - app_network
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - 1000:1000
    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
