/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Play } from 'react-feather'
import IconBase from './../../IconBase'

function IconPlay(props: any) {
  return <IconBase icon={Play} {...props} />
}

export default IconPlay
