/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { XOctagon } from 'react-feather'
import IconBase from './../../IconBase'

function IconXOctagon(props: any) {
  return <IconBase icon={XOctagon} {...props} />
}

export default IconXOctagon
