/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { XOctagon } from 'react-feather'

function IconXOctagon(props: any) {
  return <IconBase icon={XOctagon} {...props} />
}

export default IconXOctagon
