/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Printer } from 'react-feather'
import IconBase from './../../IconBase'

function IconPrinter(props: any) {
  return <IconBase icon={Printer} {...props} />
}

export default IconPrinter
