/**
* This file is generated by @wesbitty automatically
* Do Not Edit
*/
declare function IconMoreVertical(props: any): import("react/jsx-runtime").JSX.Element;
export default IconMoreVertical;
