/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { UserPlus } from 'react-feather'
import IconBase from './../../IconBase'

function IconUserPlus(props: any) {
  return <IconBase icon={UserPlus} {...props} />
}

export default IconUserPlus
