/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { GitMerge } from 'react-feather'
import IconBase from './../../IconBase'

function IconGitMerge(props: any) {
  return <IconBase icon={GitMerge} {...props} />
}

export default IconGitMerge
