/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Inbox } from 'react-feather'

function IconInbox(props: any) {
  return <IconBase icon={Inbox} {...props} />
}

export default IconInbox
