/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Delete } from 'react-feather'
import IconBase from './../../IconBase'

function IconDelete(props: any) {
  return <IconBase icon={Delete} {...props} />
}

export default IconDelete
