// DO NOT EDIT
// This file is generated by IconGenerator script
import React from 'react'
// @ts-ignore
import Icon from 'react-feather/dist/icons/log-out'
import IconBase from './../../IconBase'

function IconLogOut(props: any) {
  return <IconBase icon={Icon} {...props} />
}

export default IconLogOut
