/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { LogOut } from 'react-feather'

function IconLogOut(props: any) {
  return <IconBase icon={LogOut} {...props} />
}

export default IconLogOut
