/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { ArrowDownLeft } from 'react-feather'
import IconBase from './../../IconBase'

function IconArrowDownLeft(props: any) {
  return <IconBase icon={ArrowDownLeft} {...props} />
}

export default IconArrowDownLeft
