/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Sunrise } from 'react-feather'

function IconSunrise(props: any) {
  return <IconBase icon={Sunrise} {...props} />
}

export default IconSunrise
