/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { AlertTriangle } from 'react-feather'

function IconAlertTriangle(props: any) {
  return <IconBase icon={AlertTriangle} {...props} />
}

export default IconAlertTriangle
