/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Paperclip } from 'react-feather'

function IconPaperclip(props: any) {
  return <IconBase icon={Paperclip} {...props} />
}

export default IconPaperclip
