/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Map } from 'react-feather'

function IconMap(props: any) {
  return <IconBase icon={Map} {...props} />
}

export default IconMap
