/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { ArrowUpRight } from 'react-feather'
import IconBase from './../../IconBase'

function IconArrowUpRight(props: any) {
  return <IconBase icon={ArrowUpRight} {...props} />
}

export default IconArrowUpRight
