/**
* This file is generated by @wesbitty automatically
* Do Not Edit
*/

import React from 'react'
// @ts-ignore
import Icon from 'react-feather/dist/icons/arrow-up-right'
import IconBase from './../../IconBase'

function IconArrowUpRight(props: any) {
  return <IconBase icon={Icon} {...props} />
}

export default IconArrowUpRight
  