// DO NOT EDIT
  // This file is generated by IconGenerator script
  import React from 'react'
  // @ts-ignore
  import Icon from 'react-feather/dist/icons/refresh-ccw'
  import IconBase from '../../IconBase'

  function IconRefreshCcw(props: any) {
    return <IconBase icon={Icon} {...props} />
  }

  export default IconRefreshCcw
  