/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { RefreshCcw } from 'react-feather'

function IconRefreshCcw(props: any) {
  return <IconBase icon={RefreshCcw} {...props} />
}

export default IconRefreshCcw
