/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Dribbble } from 'react-feather'
import IconBase from './../../IconBase'

function IconDribbble(props: any) {
  return <IconBase icon={Dribbble} {...props} />
}

export default IconDribbble
