/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { PauseCircle } from 'react-feather'

function IconPauseCircle(props: any) {
  return <IconBase icon={PauseCircle} {...props} />
}

export default IconPauseCircle
