/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Rewind } from 'react-feather'

function IconRewind(props: any) {
  return <IconBase icon={Rewind} {...props} />
}

export default IconRewind
