/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Anchor } from 'react-feather'

function IconAnchor(props: any) {
  return <IconBase icon={Anchor} {...props} />
}

export default IconAnchor
