/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { AlignLeft } from 'react-feather'
import IconBase from './../../IconBase'

function IconAlignLeft(props: any) {
  return <IconBase icon={AlignLeft} {...props} />
}

export default IconAlignLeft
