/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Twitch } from 'react-feather'
import IconBase from './../../IconBase'

function IconTwitch(props: any) {
  return <IconBase icon={Twitch} {...props} />
}

export default IconTwitch
