/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Repeat } from 'react-feather'
import IconBase from './../../IconBase'

function IconRepeat(props: any) {
  return <IconBase icon={Repeat} {...props} />
}

export default IconRepeat
