/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { DivideCircle } from 'react-feather'

function IconDivideCircle(props: any) {
  return <IconBase icon={DivideCircle} {...props} />
}

export default IconDivideCircle
