/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Facebook } from 'react-feather'

function IconFacebook(props: any) {
  return <IconBase icon={Facebook} {...props} />
}

export default IconFacebook
