/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { PlusSquare } from 'react-feather'

function IconPlusSquare(props: any) {
  return <IconBase icon={PlusSquare} {...props} />
}

export default IconPlusSquare
