/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Users } from 'react-feather'

function IconUsers(props: any) {
  return <IconBase icon={Users} {...props} />
}

export default IconUsers
