/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Clock } from 'react-feather'

function IconClock(props: any) {
  return <IconBase icon={Clock} {...props} />
}

export default IconClock
