/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { PhoneMissed } from 'react-feather'

function IconPhoneMissed(props: any) {
  return <IconBase icon={PhoneMissed} {...props} />
}

export default IconPhoneMissed
