/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Moon } from 'react-feather'
import IconBase from './../../IconBase'

function IconMoon(props: any) {
  return <IconBase icon={Moon} {...props} />
}

export default IconMoon
