/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Trash2 } from 'react-feather'

function IconTrash2(props: any) {
  return <IconBase icon={Trash2} {...props} />
}

export default IconTrash2
