/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Loader } from 'react-feather'

function IconLoader(props: any) {
  return <IconBase icon={Loader} {...props} />
}

export default IconLoader
