/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Zap } from 'react-feather'

function IconZap(props: any) {
  return <IconBase icon={Zap} {...props} />
}

export default IconZap
