/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { CornerUpLeft } from 'react-feather'
import IconBase from './../../IconBase'

function IconCornerUpLeft(props: any) {
  return <IconBase icon={CornerUpLeft} {...props} />
}

export default IconCornerUpLeft
