/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { FileText } from 'react-feather'
import IconBase from './../../IconBase'

function IconFileText(props: any) {
  return <IconBase icon={FileText} {...props} />
}

export default IconFileText
