module.exports = {
  brand: {
    brand1: 'var(--colors-blue1)',
    brand2: 'var(--colors-blue2)',
    brand3: 'var(--colors-blue3)',
    brand4: 'var(--colors-blue4)',
    brand5: 'var(--colors-blue5)',
    brand6: 'var(--colors-blue6))',
    brand7: 'var(--colors-blue7)',
    brand8: 'var(--colors-blue8)',
    brand9: 'var(--colors-blue9)',
    brand10: 'var(--colors-blue10)',
    brand11: 'var(--colors-blue11)',
    brand12: 'var(--colors-blue12)',
  },
  brandDark: {
    brand1: 'hsla(153, 75%, 6%, 1)',
    brand2: 'hsla(153, 73%, 7%, 1)',
    brand3: 'hsla(154, 69%, 9%, 1)',
    brand4: 'hsla(154, 67%, 11%, 1)',
    brand5: 'hsla(154, 66%, 13%, 1)',
    brand6: 'var(--colors-sky6)',
    brand7: 'var(--colors-sky7)',
    brand8: 'var(--colors-sky8)',
    brand9: 'var(--colors-sky9)',
    brand10: 'var(--colors-sky10)',
    brand11: 'var(--colors-sky11)',
    brand12: 'var(--colors-sky-12)',
  },
  contrast: {
    'brand-hiContrast': 'var(--colors-brand-9)',
    'brand-loContrast': 'var(--colors-brand-4)',
  },
  scale: {
    scale1: 'var(--colors-slate1)',
    scale2: 'var(--colors-slate2)',
    scale3: 'var(--colors-slate3)',
    scale4: 'var(--colors-slate4)',
    scale5: 'var(--colors-slate5)',
    scale6: 'var(--colors-slate6)',
    scale7: 'var(--colors-slate7)',
    scale8: 'var(--colors-slate8)',
    scale9: 'var(--colors-slate9)',
    scale10: 'var(--colors-slate10)',
    scale11: 'var(--colors-slate11)',
    scale12: 'var(--colors-slate12)',
  },
  scaleA: {
    scaleA1: 'var(--colors-slateA1)',
    scaleA2: 'var(--colors-slateA2)',
    scaleA3: 'var(--colors-slateA3)',
    scaleA4: 'var(--colors-slateA4)',
    scaleA5: 'var(--colors-slateA5)',
    scaleA6: 'var(--colors-slateA6)',
    scaleA7: 'var(--colors-slateA7)',
    scaleA8: 'var(--colors-slateA8)',
    scaleA9: 'var(--colors-slateA9)',
    scaleA10: 'var(--colors-slateA10)',
    scaleA11: 'var(--colors-slateA11)',
    scaleA12: 'var(--colors-slateA12)',
  },
  scaleDark: {
    scale1: 'var(--colors-gray1)',
    scale2: 'var(--colors-gray2)',
    scale3: 'var(--colors-gray3)',
    scale4: 'var(--colors-gray4)',
    scale5: 'var(--colors-gray5)',
    scale6: 'var(--colors-gray6)',
    scale7: 'var(--colors-gray7)',
    scale8: 'var(--colors-gray8)',
    scale9: 'var(--colors-gray9)',
    scale10: 'var(--colors-gray10)',
    scale11: '#bbbbbb',
    scale12: 'var(--colors-gray12)',
  },
  scaleADark: {
    scaleA1: 'var(--colors-grayA1)',
    scaleA2: 'var(--colors-grayA2)',
    scaleA3: 'var(--colors-grayA3)',
    scaleA4: 'var(--colors-grayA4)',
    scaleA5: 'var(--colors-grayA5)',
    scaleA6: 'var(--colors-grayA6)',
    scaleA7: 'var(--colors-grayA7)',
    scaleA8: 'var(--colors-grayA8)',
    scaleA9: 'var(--colors-grayA9)',
    scaleA10: 'var(--colors-grayA10)',
    scaleA11: 'var(--colors-grayA11)',
    scaleA12: 'var(--colors-grayA12)',
  },
}
