/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Gift } from 'react-feather'
import IconBase from './../../IconBase'

function IconGift(props: any) {
  return <IconBase icon={Gift} {...props} />
}

export default IconGift
