/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Music } from 'react-feather'
import IconBase from './../../IconBase'

function IconMusic(props: any) {
  return <IconBase icon={Music} {...props} />
}

export default IconMusic
