/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { XCircle } from 'react-feather'

function IconXCircle(props: any) {
  return <IconBase icon={XCircle} {...props} />
}

export default IconXCircle
