/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { ArrowUpLeft } from 'react-feather'

function IconArrowUpLeft(props: any) {
  return <IconBase icon={ArrowUpLeft} {...props} />
}

export default IconArrowUpLeft
