/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { EyeOff } from 'react-feather'

function IconEyeOff(props: any) {
  return <IconBase icon={EyeOff} {...props} />
}

export default IconEyeOff
