/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Eye } from 'react-feather'
import IconBase from './../../IconBase'

function IconEye(props: any) {
  return <IconBase icon={Eye} {...props} />
}

export default IconEye
