/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { PhoneForwarded } from 'react-feather'

function IconPhoneForwarded(props: any) {
  return <IconBase icon={PhoneForwarded} {...props} />
}

export default IconPhoneForwarded
