/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { PhoneForwarded } from 'react-feather'
import IconBase from './../../IconBase'

function IconPhoneForwarded(props: any) {
  return <IconBase icon={PhoneForwarded} {...props} />
}

export default IconPhoneForwarded
