/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { MessageSquare } from 'react-feather'

function IconMessageSquare(props: any) {
  return <IconBase icon={MessageSquare} {...props} />
}

export default IconMessageSquare
