/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { FolderPlus } from 'react-feather'

function IconFolderPlus(props: any) {
  return <IconBase icon={FolderPlus} {...props} />
}

export default IconFolderPlus
