/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { MousePointer } from 'react-feather'

function IconMousePointer(props: any) {
  return <IconBase icon={MousePointer} {...props} />
}

export default IconMousePointer
