/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Bold } from 'react-feather'

function IconBold(props: any) {
  return <IconBase icon={Bold} {...props} />
}

export default IconBold
