/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { ArrowDown } from 'react-feather'

function IconArrowDown(props: any) {
  return <IconBase icon={ArrowDown} {...props} />
}

export default IconArrowDown
