/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Minus } from 'react-feather'

function IconMinus(props: any) {
  return <IconBase icon={Minus} {...props} />
}

export default IconMinus
