/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Tv } from 'react-feather'

function IconTv(props: any) {
  return <IconBase icon={Tv} {...props} />
}

export default IconTv
