/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Plus } from 'react-feather'
import IconBase from './../../IconBase'

function IconPlus(props: any) {
  return <IconBase icon={Plus} {...props} />
}

export default IconPlus
