/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Key } from 'react-feather'
import IconBase from './../../IconBase'

function IconKey(props: any) {
  return <IconBase icon={Key} {...props} />
}

export default IconKey
