/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { CloudSnow } from 'react-feather'

function IconCloudSnow(props: any) {
  return <IconBase icon={CloudSnow} {...props} />
}

export default IconCloudSnow
