/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Voicemail } from 'react-feather'

function IconVoicemail(props: any) {
  return <IconBase icon={Voicemail} {...props} />
}

export default IconVoicemail
