// DO NOT EDIT
  // This file is generated by IconGenerator script
  import React from 'react'
  // @ts-ignore
  import Icon from 'react-feather/dist/icons/maximize-2'
  import IconBase from '../../IconBase'

  function IconMaximize2(props: any) {
    return <IconBase icon={Icon} {...props} />
  }

  export default IconMaximize2
  