/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Maximize2 } from 'react-feather'

function IconMaximize2(props: any) {
  return <IconBase icon={Maximize2} {...props} />
}

export default IconMaximize2
