/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { PenTool } from 'react-feather'

function IconPenTool(props: any) {
  return <IconBase icon={PenTool} {...props} />
}

export default IconPenTool
