/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { ToggleLeft } from 'react-feather'
import IconBase from './../../IconBase'

function IconToggleLeft(props: any) {
  return <IconBase icon={ToggleLeft} {...props} />
}

export default IconToggleLeft
