/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Flag } from 'react-feather'

function IconFlag(props: any) {
  return <IconBase icon={Flag} {...props} />
}

export default IconFlag
