/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Flag } from 'react-feather'
import IconBase from './../../IconBase'

function IconFlag(props: any) {
  return <IconBase icon={Flag} {...props} />
}

export default IconFlag
