/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { PhoneOutgoing } from 'react-feather'
import IconBase from './../../IconBase'

function IconPhoneOutgoing(props: any) {
  return <IconBase icon={PhoneOutgoing} {...props} />
}

export default IconPhoneOutgoing
