/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Cloud } from 'react-feather'

function IconCloud(props: any) {
  return <IconBase icon={Cloud} {...props} />
}

export default IconCloud
