/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { ZoomIn } from 'react-feather'

function IconZoomIn(props: any) {
  return <IconBase icon={ZoomIn} {...props} />
}

export default IconZoomIn
