/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { HelpCircle } from 'react-feather'

function IconHelpCircle(props: any) {
  return <IconBase icon={HelpCircle} {...props} />
}

export default IconHelpCircle
