/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Search } from 'react-feather'
import IconBase from './../../IconBase'

function IconSearch(props: any) {
  return <IconBase icon={Search} {...props} />
}

export default IconSearch
