/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Cpu } from 'react-feather'

function IconCpu(props: any) {
  return <IconBase icon={Cpu} {...props} />
}

export default IconCpu
