/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { ChevronsDown } from 'react-feather'

function IconChevronsDown(props: any) {
  return <IconBase icon={ChevronsDown} {...props} />
}

export default IconChevronsDown
