/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Smartphone } from 'react-feather'

function IconSmartphone(props: any) {
  return <IconBase icon={Smartphone} {...props} />
}

export default IconSmartphone
