/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { MoreHorizontal } from 'react-feather'

function IconMoreHorizontal(props: any) {
  return <IconBase icon={MoreHorizontal} {...props} />
}

export default IconMoreHorizontal
