/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { CameraOff } from 'react-feather'
import IconBase from './../../IconBase'

function IconCameraOff(props: any) {
  return <IconBase icon={CameraOff} {...props} />
}

export default IconCameraOff
