/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { CheckSquare } from 'react-feather'
import IconBase from './../../IconBase'

function IconCheckSquare(props: any) {
  return <IconBase icon={CheckSquare} {...props} />
}

export default IconCheckSquare
