/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { FolderMinus } from 'react-feather'

function IconFolderMinus(props: any) {
  return <IconBase icon={FolderMinus} {...props} />
}

export default IconFolderMinus
