/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Droplet } from 'react-feather'
import IconBase from './../../IconBase'

function IconDroplet(props: any) {
  return <IconBase icon={Droplet} {...props} />
}

export default IconDroplet
