/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { DivideSquare } from 'react-feather'
import IconBase from './../../IconBase'

function IconDivideSquare(props: any) {
  return <IconBase icon={DivideSquare} {...props} />
}

export default IconDivideSquare
