/**
* This file is generated by @wesbitty automatically
* Do Not Edit
*/
declare function IconDivideCircle(props: any): import("react/jsx-runtime").JSX.Element;
export default IconDivideCircle;
