/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Activity } from 'react-feather'

function IconActivity(props: any) {
  return <IconBase icon={Activity} {...props} />
}

export default IconActivity
