/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Layout } from 'react-feather'

function IconLayout(props: any) {
  return <IconBase icon={Layout} {...props} />
}

export default IconLayout
