/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Target } from 'react-feather'
import IconBase from './../../IconBase'

function IconTarget(props: any) {
  return <IconBase icon={Target} {...props} />
}

export default IconTarget
