/**
* This file is generated by @wesbitty automatically
* Do Not Edit
*/
declare function IconDivideSquare(props: any): import("react/jsx-runtime").JSX.Element;
export default IconDivideSquare;
