/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { CloudOff } from 'react-feather'

function IconCloudOff(props: any) {
  return <IconBase icon={CloudOff} {...props} />
}

export default IconCloudOff
