/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Briefcase } from 'react-feather'

function IconBriefcase(props: any) {
  return <IconBase icon={Briefcase} {...props} />
}

export default IconBriefcase
