/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Codesandbox } from 'react-feather'
import IconBase from './../../IconBase'

function IconCodesandbox(props: any) {
  return <IconBase icon={Codesandbox} {...props} />
}

export default IconCodesandbox
