/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Hexagon } from 'react-feather'
import IconBase from './../../IconBase'

function IconHexagon(props: any) {
  return <IconBase icon={Hexagon} {...props} />
}

export default IconHexagon
