/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Filter } from 'react-feather'

function IconFilter(props: any) {
  return <IconBase icon={Filter} {...props} />
}

export default IconFilter
