
  /*
  * This file is generated by @wesbitty automatically
  * Do Not Edit
  */

  import React from 'react'
  // @ts-ignore
  import Icon from 'react-feather/dist/icons/filter'
  import IconBase from './../../IconBase'

  function IconFilter(props: any) {
    return <IconBase icon={Icon} {...props} />
  }

  export default IconFilter
  