/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Shuffle } from 'react-feather'
import IconBase from './../../IconBase'

function IconShuffle(props: any) {
  return <IconBase icon={Shuffle} {...props} />
}

export default IconShuffle
