/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Shuffle } from 'react-feather'

function IconShuffle(props: any) {
  return <IconBase icon={Shuffle} {...props} />
}

export default IconShuffle
