/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Link } from 'react-feather'

function IconLink(props: any) {
  return <IconBase icon={Link} {...props} />
}

export default IconLink
