// DO NOT EDIT
  // This file is generated by IconGenerator script
  import React from 'react'
  // @ts-ignore
  import Icon from 'react-feather/dist/icons/link'
  import IconBase from './../../IconBase'

  function IconLink(props: any) {
    return <IconBase icon={Icon} {...props} />
  }

  export default IconLink
  