/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { List } from 'react-feather'

function IconList(props: any) {
  return <IconBase icon={List} {...props} />
}

export default IconList
