/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Share } from 'react-feather'

function IconShare(props: any) {
  return <IconBase icon={Share} {...props} />
}

export default IconShare
