/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Linkedin } from 'react-feather'
import IconBase from './../../IconBase'

function IconLinkedin(props: any) {
  return <IconBase icon={Linkedin} {...props} />
}

export default IconLinkedin
