/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { LogIn } from 'react-feather'

function IconLogIn(props: any) {
  return <IconBase icon={LogIn} {...props} />
}

export default IconLogIn
