/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Info } from 'react-feather'

function IconInfo(props: any) {
  return <IconBase icon={Info} {...props} />
}

export default IconInfo
