/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Info } from 'react-feather'
import IconBase from './../../IconBase'

function IconInfo(props: any) {
  return <IconBase icon={Info} {...props} />
}

export default IconInfo
