/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Folder } from 'react-feather'
import IconBase from './../../IconBase'

function IconFolder(props: any) {
  return <IconBase icon={Folder} {...props} />
}

export default IconFolder
