/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Figma } from 'react-feather'

function IconFigma(props: any) {
  return <IconBase icon={Figma} {...props} />
}

export default IconFigma
