/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Mic } from 'react-feather'

function IconMic(props: any) {
  return <IconBase icon={Mic} {...props} />
}

export default IconMic
