/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Sidebar } from 'react-feather'
import IconBase from './../../IconBase'

function IconSidebar(props: any) {
  return <IconBase icon={Sidebar} {...props} />
}

export default IconSidebar
