/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Power } from 'react-feather'

function IconPower(props: any) {
  return <IconBase icon={Power} {...props} />
}

export default IconPower
