/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { VideoOff } from 'react-feather'

function IconVideoOff(props: any) {
  return <IconBase icon={VideoOff} {...props} />
}

export default IconVideoOff
