/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Thermometer } from 'react-feather'

function IconThermometer(props: any) {
  return <IconBase icon={Thermometer} {...props} />
}

export default IconThermometer
