/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Speaker } from 'react-feather'

function IconSpeaker(props: any) {
  return <IconBase icon={Speaker} {...props} />
}

export default IconSpeaker
