/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Package } from 'react-feather'

function IconPackage(props: any) {
  return <IconBase icon={Package} {...props} />
}

export default IconPackage
