/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Codepen } from 'react-feather'

function IconCodepen(props: any) {
  return <IconBase icon={Codepen} {...props} />
}

export default IconCodepen
