/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { User } from 'react-feather'

function IconUser(props: any) {
  return <IconBase icon={User} {...props} />
}

export default IconUser
