/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Check } from 'react-feather'

function IconCheck(props: any) {
  return <IconBase icon={Check} {...props} />
}

export default IconCheck
