/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { RotateCw } from 'react-feather'

function IconRotateCw(props: any) {
  return <IconBase icon={RotateCw} {...props} />
}

export default IconRotateCw
