/**
* This file is generated by @wesbitty automatically
* Do Not Edit
*/
declare function IconDownloadCloud(props: any): import("react/jsx-runtime").JSX.Element;
export default IconDownloadCloud;
