/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { ThumbsDown } from 'react-feather'
import IconBase from './../../IconBase'

function IconThumbsDown(props: any) {
  return <IconBase icon={ThumbsDown} {...props} />
}

export default IconThumbsDown
