/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Command } from 'react-feather'

function IconCommand(props: any) {
  return <IconBase icon={Command} {...props} />
}

export default IconCommand
