/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Square } from 'react-feather'
import IconBase from './../../IconBase'

function IconSquare(props: any) {
  return <IconBase icon={Square} {...props} />
}

export default IconSquare
