/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { CloudLightning } from 'react-feather'

function IconCloudLightning(props: any) {
  return <IconBase icon={CloudLightning} {...props} />
}

export default IconCloudLightning
