/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Pocket } from 'react-feather'
import IconBase from './../../IconBase'

function IconPocket(props: any) {
  return <IconBase icon={Pocket} {...props} />
}

export default IconPocket
