/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Calendar } from 'react-feather'

function IconCalendar(props: any) {
  return <IconBase icon={Calendar} {...props} />
}

export default IconCalendar
