/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { GitBranch } from 'react-feather'

function IconGitBranch(props: any) {
  return <IconBase icon={GitBranch} {...props} />
}

export default IconGitBranch
