/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { HardDrive } from 'react-feather'

function IconHardDrive(props: any) {
  return <IconBase icon={HardDrive} {...props} />
}

export default IconHardDrive
