/**
* This file is generated by @wesbitty automatically
* Do Not Edit
*/

import React from 'react'
// @ts-ignore
import Icon from 'react-feather/dist/icons/volume-1'
import IconBase from './../../IconBase'

function IconVolume1(props: any) {
  return <IconBase icon={Icon} {...props} />
}

export default IconVolume1
  