/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Volume1 } from 'react-feather'

function IconVolume1(props: any) {
  return <IconBase icon={Volume1} {...props} />
}

export default IconVolume1
