/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { ShieldOff } from 'react-feather'

function IconShieldOff(props: any) {
  return <IconBase icon={ShieldOff} {...props} />
}

export default IconShieldOff
