/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Grid } from 'react-feather'
import IconBase from './../../IconBase'

function IconGrid(props: any) {
  return <IconBase icon={Grid} {...props} />
}

export default IconGrid
