/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { CornerLeftUp } from 'react-feather'
import IconBase from './../../IconBase'

function IconCornerLeftUp(props: any) {
  return <IconBase icon={CornerLeftUp} {...props} />
}

export default IconCornerLeftUp
