/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { AlignRight } from 'react-feather'
import IconBase from './../../IconBase'

function IconAlignRight(props: any) {
  return <IconBase icon={AlignRight} {...props} />
}

export default IconAlignRight
