/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Server } from 'react-feather'

function IconServer(props: any) {
  return <IconBase icon={Server} {...props} />
}

export default IconServer
