// DO NOT EDIT
  // This file is generated by IconGenerator script
  import React from 'react'
  // @ts-ignore
  import Icon from 'react-feather/dist/icons/disc'
  import IconBase from './../../IconBase'

  function IconDisc(props: any) {
    return <IconBase icon={Icon} {...props} />
  }

  export default IconDisc
  