/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Disc } from 'react-feather'

function IconDisc(props: any) {
  return <IconBase icon={Disc} {...props} />
}

export default IconDisc
