/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { LifeBuoy } from 'react-feather'

function IconLifeBuoy(props: any) {
  return <IconBase icon={LifeBuoy} {...props} />
}

export default IconLifeBuoy
