/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { MapPin } from 'react-feather'

function IconMapPin(props: any) {
  return <IconBase icon={MapPin} {...props} />
}

export default IconMapPin
