/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { ChevronDown } from 'react-feather'

function IconChevronDown(props: any) {
  return <IconBase icon={ChevronDown} {...props} />
}

export default IconChevronDown
