/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Minimize } from 'react-feather'

function IconMinimize(props: any) {
  return <IconBase icon={Minimize} {...props} />
}

export default IconMinimize
