/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Frown } from 'react-feather'
import IconBase from './../../IconBase'

function IconFrown(props: any) {
  return <IconBase icon={Frown} {...props} />
}

export default IconFrown
