/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Navigation2 } from 'react-feather'

function IconNavigation2(props: any) {
  return <IconBase icon={Navigation2} {...props} />
}

export default IconNavigation2
