/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Crop } from 'react-feather'

function IconCrop(props: any) {
  return <IconBase icon={Crop} {...props} />
}

export default IconCrop
