/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Headphones } from 'react-feather'

function IconHeadphones(props: any) {
  return <IconBase icon={Headphones} {...props} />
}

export default IconHeadphones
