/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Star } from 'react-feather'
import IconBase from './../../IconBase'

function IconStar(props: any) {
  return <IconBase icon={Star} {...props} />
}

export default IconStar
