/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Link2 } from 'react-feather'

function IconLink2(props: any) {
  return <IconBase icon={Link2} {...props} />
}

export default IconLink2
