/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { ZoomOut } from 'react-feather'

function IconZoomOut(props: any) {
  return <IconBase icon={ZoomOut} {...props} />
}

export default IconZoomOut
