/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Tag } from 'react-feather'

function IconTag(props: any) {
  return <IconBase icon={Tag} {...props} />
}

export default IconTag
