/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Move } from 'react-feather'

function IconMove(props: any) {
  return <IconBase icon={Move} {...props} />
}

export default IconMove
