/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { TrendingDown } from 'react-feather'
import IconBase from './../../IconBase'

function IconTrendingDown(props: any) {
  return <IconBase icon={TrendingDown} {...props} />
}

export default IconTrendingDown
