/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Divide } from 'react-feather'
import IconBase from './../../IconBase'

function IconDivide(props: any) {
  return <IconBase icon={Divide} {...props} />
}

export default IconDivide
