/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Aperture } from 'react-feather'

function IconAperture(props: any) {
  return <IconBase icon={Aperture} {...props} />
}

export default IconAperture
