/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { CloudDrizzle } from 'react-feather'
import IconBase from './../../IconBase'

function IconCloudDrizzle(props: any) {
  return <IconBase icon={CloudDrizzle} {...props} />
}

export default IconCloudDrizzle
