/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { PhoneIncoming } from 'react-feather'
import IconBase from './../../IconBase'

function IconPhoneIncoming(props: any) {
  return <IconBase icon={PhoneIncoming} {...props} />
}

export default IconPhoneIncoming
