/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { MoreVertical } from 'react-feather'

function IconMoreVertical(props: any) {
  return <IconBase icon={MoreVertical} {...props} />
}

export default IconMoreVertical
