/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */
declare function IconCornerRightUp(
  props: any
): import('react/jsx-runtime').JSX.Element
export default IconCornerRightUp
