/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Feather } from 'react-feather'
import IconBase from './../../IconBase'

function IconFeather(props: any) {
  return <IconBase icon={Feather} {...props} />
}

export default IconFeather
