/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { ShoppingBag } from 'react-feather'
import IconBase from './../../IconBase'

function IconShoppingBag(props: any) {
  return <IconBase icon={ShoppingBag} {...props} />
}

export default IconShoppingBag
