/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { BatteryCharging } from 'react-feather'
import IconBase from './../../IconBase'

function IconBatteryCharging(props: any) {
  return <IconBase icon={BatteryCharging} {...props} />
}

export default IconBatteryCharging
