/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { BatteryCharging } from 'react-feather'

function IconBatteryCharging(props: any) {
  return <IconBase icon={BatteryCharging} {...props} />
}

export default IconBatteryCharging
