/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Slash } from 'react-feather'
import IconBase from './../../IconBase'

function IconSlash(props: any) {
  return <IconBase icon={Slash} {...props} />
}

export default IconSlash
