/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { MinusSquare } from 'react-feather'

function IconMinusSquare(props: any) {
  return <IconBase icon={MinusSquare} {...props} />
}

export default IconMinusSquare
