/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Framer } from 'react-feather'
import IconBase from './../../IconBase'

function IconFramer(props: any) {
  return <IconBase icon={Framer} {...props} />
}

export default IconFramer
