/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { ChevronUp } from 'react-feather'
import IconBase from './../../IconBase'

function IconChevronUp(props: any) {
  return <IconBase icon={ChevronUp} {...props} />
}

export default IconChevronUp
