/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Wind } from 'react-feather'

function IconWind(props: any) {
  return <IconBase icon={Wind} {...props} />
}

export default IconWind
