/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Instagram } from 'react-feather'

function IconInstagram(props: any) {
  return <IconBase icon={Instagram} {...props} />
}

export default IconInstagram
