/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Trash } from 'react-feather'

function IconTrash(props: any) {
  return <IconBase icon={Trash} {...props} />
}

export default IconTrash
