/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Columns } from 'react-feather'

function IconColumns(props: any) {
  return <IconBase icon={Columns} {...props} />
}

export default IconColumns
