/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Slack } from 'react-feather'

function IconSlack(props: any) {
  return <IconBase icon={Slack} {...props} />
}

export default IconSlack
