/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { SkipBack } from 'react-feather'

function IconSkipBack(props: any) {
  return <IconBase icon={SkipBack} {...props} />
}

export default IconSkipBack
