/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { CornerRightDown } from 'react-feather'
import IconBase from './../../IconBase'

function IconCornerRightDown(props: any) {
  return <IconBase icon={CornerRightDown} {...props} />
}

export default IconCornerRightDown
