/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { CornerRightDown } from 'react-feather'

function IconCornerRightDown(props: any) {
  return <IconBase icon={CornerRightDown} {...props} />
}

export default IconCornerRightDown
