/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { PlusCircle } from 'react-feather'

function IconPlusCircle(props: any) {
  return <IconBase icon={PlusCircle} {...props} />
}

export default IconPlusCircle
