/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { ChevronRight } from 'react-feather'
import IconBase from './../../IconBase'

function IconChevronRight(props: any) {
  return <IconBase icon={ChevronRight} {...props} />
}

export default IconChevronRight
