/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Gitlab } from 'react-feather'
import IconBase from './../../IconBase'

function IconGitlab(props: any) {
  return <IconBase icon={Gitlab} {...props} />
}

export default IconGitlab
