/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Navigation } from 'react-feather'
import IconBase from './../../IconBase'

function IconNavigation(props: any) {
  return <IconBase icon={Navigation} {...props} />
}

export default IconNavigation
