/**
* This file is generated by @wesbitty automatically
* Do Not Edit
*/
declare function IconCornerUpLeft(props: any): import("react/jsx-runtime").JSX.Element;
export default IconCornerUpLeft;
