/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Type } from 'react-feather'

function IconType(props: any) {
  return <IconBase icon={Type} {...props} />
}

export default IconType
