/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { GitCommit } from 'react-feather'
import IconBase from './../../IconBase'

function IconGitCommit(props: any) {
  return <IconBase icon={GitCommit} {...props} />
}

export default IconGitCommit
