/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Wifi } from 'react-feather'

function IconWifi(props: any) {
  return <IconBase icon={Wifi} {...props} />
}

export default IconWifi
