/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Volume2 } from 'react-feather'

function IconVolume2(props: any) {
  return <IconBase icon={Volume2} {...props} />
}

export default IconVolume2
