/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { TrendingUp } from 'react-feather'

function IconTrendingUp(props: any) {
  return <IconBase icon={TrendingUp} {...props} />
}

export default IconTrendingUp
