/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Italic } from 'react-feather'
import IconBase from './../../IconBase'

function IconItalic(props: any) {
  return <IconBase icon={Italic} {...props} />
}

export default IconItalic
