/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { VolumeX } from 'react-feather'
import IconBase from './../../IconBase'

function IconVolumeX(props: any) {
  return <IconBase icon={VolumeX} {...props} />
}

export default IconVolumeX
