/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Maximize } from 'react-feather'

function IconMaximize(props: any) {
  return <IconBase icon={Maximize} {...props} />
}

export default IconMaximize
