/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import React from 'react'
// @ts-ignore
import Icon from 'react-feather/dist/icons/maximize'
import IconBase from './../../IconBase'

function IconMaximize(props: any) {
  return <IconBase icon={Icon} {...props} />
}

export default IconMaximize
