/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { UserX } from 'react-feather'

function IconUserX(props: any) {
  return <IconBase icon={UserX} {...props} />
}

export default IconUserX
