/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { CreditCard } from 'react-feather'
import IconBase from './../../IconBase'

function IconCreditCard(props: any) {
  return <IconBase icon={CreditCard} {...props} />
}

export default IconCreditCard
