/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Lock } from 'react-feather'

function IconLock(props: any) {
  return <IconBase icon={Lock} {...props} />
}

export default IconLock
