/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { X } from 'react-feather'

function IconX(props: any) {
  return <IconBase icon={X} {...props} />
}

export default IconX
