/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { ShoppingCart } from 'react-feather'

function IconShoppingCart(props: any) {
  return <IconBase icon={ShoppingCart} {...props} />
}

export default IconShoppingCart
