/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { ThumbsUp } from 'react-feather'

function IconThumbsUp(props: any) {
  return <IconBase icon={ThumbsUp} {...props} />
}

export default IconThumbsUp
