/**
* This file is generated by @wesbitty automatically
* Do Not Edit
*/
declare function IconMessageCircle(props: any): import("react/jsx-runtime").JSX.Element;
export default IconMessageCircle;
