/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Crosshair } from 'react-feather'
import IconBase from './../../IconBase'

function IconCrosshair(props: any) {
  return <IconBase icon={Crosshair} {...props} />
}

export default IconCrosshair
