/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { RefreshCw } from 'react-feather'

function IconRefreshCw(props: any) {
  return <IconBase icon={RefreshCw} {...props} />
}

export default IconRefreshCw
