/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Home } from 'react-feather'

function IconHome(props: any) {
  return <IconBase icon={Home} {...props} />
}

export default IconHome
