/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Video } from 'react-feather'

function IconVideo(props: any) {
  return <IconBase icon={Video} {...props} />
}

export default IconVideo
