/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Share2 } from 'react-feather'

function IconShare2(props: any) {
  return <IconBase icon={Share2} {...props} />
}

export default IconShare2
