/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { SkipForward } from 'react-feather'

function IconSkipForward(props: any) {
  return <IconBase icon={SkipForward} {...props} />
}

export default IconSkipForward
