/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Rss } from 'react-feather'
import IconBase from './../../IconBase'

function IconRss(props: any) {
  return <IconBase icon={Rss} {...props} />
}

export default IconRss
