/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { ArrowLeftCircle } from 'react-feather'
import IconBase from './../../IconBase'

function IconArrowLeftCircle(props: any) {
  return <IconBase icon={ArrowLeftCircle} {...props} />
}

export default IconArrowLeftCircle
