// DO NOT EDIT
// This file is generated by IconGenerator script
import React from 'react'
// @ts-ignore
import Icon from 'react-feather/dist/icons/arrow-left-circle'
import IconBase from './../../IconBase'

function IconArrowLeftCircle(props: any) {
  return <IconBase icon={Icon} {...props} />
}

export default IconArrowLeftCircle
