/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { AlignJustify } from 'react-feather'

function IconAlignJustify(props: any) {
  return <IconBase icon={AlignJustify} {...props} />
}

export default IconAlignJustify
