/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Twitter } from 'react-feather'

function IconTwitter(props: any) {
  return <IconBase icon={Twitter} {...props} />
}

export default IconTwitter
