/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Twitter } from 'react-feather'
import IconBase from './../../IconBase'

function IconTwitter(props: any) {
  return <IconBase icon={Twitter} {...props} />
}

export default IconTwitter
