/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { ChevronsRight } from 'react-feather'
import IconBase from './../../IconBase'

function IconChevronsRight(props: any) {
  return <IconBase icon={ChevronsRight} {...props} />
}

export default IconChevronsRight
