/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { PhoneCall } from 'react-feather'

function IconPhoneCall(props: any) {
  return <IconBase icon={PhoneCall} {...props} />
}

export default IconPhoneCall
