/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Edit3 } from 'react-feather'
import IconBase from './../../IconBase'

function IconEdit3(props: any) {
  return <IconBase icon={Edit3} {...props} />
}

export default IconEdit3
