/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Code } from 'react-feather'

function IconCode(props: any) {
  return <IconBase icon={Code} {...props} />
}

export default IconCode
