/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { ChevronsLeft } from 'react-feather'

function IconChevronsLeft(props: any) {
  return <IconBase icon={ChevronsLeft} {...props} />
}

export default IconChevronsLeft
