/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { ZapOff } from 'react-feather'
import IconBase from './../../IconBase'

function IconZapOff(props: any) {
  return <IconBase icon={ZapOff} {...props} />
}

export default IconZapOff
