/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { ArrowUp } from 'react-feather'
import IconBase from './../../IconBase'

function IconArrowUp(props: any) {
  return <IconBase icon={ArrowUp} {...props} />
}

export default IconArrowUp
