/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { AlertOctagon } from 'react-feather'

function IconAlertOctagon(props: any) {
  return <IconBase icon={AlertOctagon} {...props} />
}

export default IconAlertOctagon
