/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { MinusCircle } from 'react-feather'

function IconMinusCircle(props: any) {
  return <IconBase icon={MinusCircle} {...props} />
}

export default IconMinusCircle
