/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { PlayCircle } from 'react-feather'

function IconPlayCircle(props: any) {
  return <IconBase icon={PlayCircle} {...props} />
}

export default IconPlayCircle
