/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Watch } from 'react-feather'

function IconWatch(props: any) {
  return <IconBase icon={Watch} {...props} />
}

export default IconWatch
