/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { DollarSign } from 'react-feather'
import IconBase from './../../IconBase'

function IconDollarSign(props: any) {
  return <IconBase icon={DollarSign} {...props} />
}

export default IconDollarSign
