/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Award } from 'react-feather'
import IconBase from './../../IconBase'

function IconAward(props: any) {
  return <IconBase icon={Award} {...props} />
}

export default IconAward
