/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { ToggleRight } from 'react-feather'

function IconToggleRight(props: any) {
  return <IconBase icon={ToggleRight} {...props} />
}

export default IconToggleRight
