/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Sun } from 'react-feather'

function IconSun(props: any) {
  return <IconBase icon={Sun} {...props} />
}

export default IconSun
