/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { MicOff } from 'react-feather'
import IconBase from './../../IconBase'

function IconMicOff(props: any) {
  return <IconBase icon={MicOff} {...props} />
}

export default IconMicOff
