/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Edit2 } from 'react-feather'

function IconEdit2(props: any) {
  return <IconBase icon={Edit2} {...props} />
}

export default IconEdit2
