/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Scissors } from 'react-feather'
import IconBase from './../../IconBase'

function IconScissors(props: any) {
  return <IconBase icon={Scissors} {...props} />
}

export default IconScissors
