/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Scissors } from 'react-feather'

function IconScissors(props: any) {
  return <IconBase icon={Scissors} {...props} />
}

export default IconScissors
