/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Sliders } from 'react-feather'

function IconSliders(props: any) {
  return <IconBase icon={Sliders} {...props} />
}

export default IconSliders
