// DO NOT EDIT
  // This file is generated by IconGenerator script
  import React from 'react'
  // @ts-ignore
  import Icon from 'react-feather/dist/icons/wifi-off'
  import IconBase from '../../IconBase'

  function IconWifiOff(props: any) {
    return <IconBase icon={Icon} {...props} />
  }

  export default IconWifiOff
  