/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { WifiOff } from 'react-feather'

function IconWifiOff(props: any) {
  return <IconBase icon={WifiOff} {...props} />
}

export default IconWifiOff
