/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Bluetooth } from 'react-feather'

function IconBluetooth(props: any) {
  return <IconBase icon={Bluetooth} {...props} />
}

export default IconBluetooth
