/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { ArrowRightCircle } from 'react-feather'
import IconBase from './../../IconBase'

function IconArrowRightCircle(props: any) {
  return <IconBase icon={ArrowRightCircle} {...props} />
}

export default IconArrowRightCircle
