/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Book } from 'react-feather'
import IconBase from './../../IconBase'

function IconBook(props: any) {
  return <IconBase icon={Book} {...props} />
}

export default IconBook
