/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { XSquare } from 'react-feather'

function IconXSquare(props: any) {
  return <IconBase icon={XSquare} {...props} />
}

export default IconXSquare
