declare namespace _default {
  const IconActivity: string
  const IconAirplay: string
  const IconAlertCircle: string
  const IconAlertOctagon: string
  const IconAlertTriangle: string
  const IconAlignCenter: string
  const IconAlignJustify: string
  const IconAlignLeft: string
  const IconAlignRight: string
  const IconAnchor: string
  const IconAperture: string
  const IconArchive: string
  const IconArrowDownCircle: string
  const IconArrowDownLeft: string
  const IconArrowDownRight: string
  const IconArrowDown: string
  const IconArrowLeftCircle: string
  const IconArrowLeft: string
  const IconArrowRightCircle: string
  const IconArrowRight: string
  const IconArrowUpCircle: string
  const IconArrowUpLeft: string
  const IconArrowUpRight: string
  const IconArrowUp: string
  const IconAtSign: string
  const IconAward: string
  const IconBarChart2: string
  const IconBarChart: string
  const IconBatteryCharging: string
  const IconBattery: string
  const IconBellOff: string
  const IconBell: string
  const IconBluetooth: string
  const IconBold: string
  const IconBookOpen: string
  const IconBook: string
  const IconBookmark: string
  const IconBox: string
  const IconBriefcase: string
  const IconCalendar: string
  const IconCameraOff: string
  const IconCamera: string
  const IconCast: string
  const IconCheckCircle: string
  const IconCheckSquare: string
  const IconCheck: string
  const IconChevronDown: string
  const IconChevronLeft: string
  const IconChevronRight: string
  const IconChevronUp: string
  const IconChevronsDown: string
  const IconChevronsLeft: string
  const IconChevronsRight: string
  const IconChevronsUp: string
  const IconChrome: string
  const IconCircle: string
  const IconClipboard: string
  const IconClock: string
  const IconCloudDrizzle: string
  const IconCloudLightning: string
  const IconCloudOff: string
  const IconCloudRain: string
  const IconCloudSnow: string
  const IconCloud: string
  const IconCode: string
  const IconCodepen: string
  const IconCodesandbox: string
  const IconCoffee: string
  const IconColumns: string
  const IconCommand: string
  const IconCompass: string
  const IconCopy: string
  const IconCornerDownLeft: string
  const IconCornerDownRight: string
  const IconCornerLeftDown: string
  const IconCornerLeftUp: string
  const IconCornerRightDown: string
  const IconCornerRightUp: string
  const IconCornerUpLeft: string
  const IconCornerUpRight: string
  const IconCpu: string
  const IconCreditCard: string
  const IconCrop: string
  const IconCrosshair: string
  const IconDatabase: string
  const IconDelete: string
  const IconDisc: string
  const IconDivideCircle: string
  const IconDivideSquare: string
  const IconDivide: string
  const IconDollarSign: string
  const IconDownloadCloud: string
  const IconDownload: string
  const IconDribbble: string
  const IconDroplet: string
  const IconEdit2: string
  const IconEdit3: string
  const IconEdit: string
  const IconExternalLink: string
  const IconEyeOff: string
  const IconEye: string
  const IconFacebook: string
  const IconFastForward: string
  const IconFeather: string
  const IconFigma: string
  const IconFileMinus: string
  const IconFilePlus: string
  const IconFileText: string
  const IconFile: string
  const IconFilm: string
  const IconFilter: string
  const IconFlag: string
  const IconFolderMinus: string
  const IconFolderPlus: string
  const IconFolder: string
  const IconFramer: string
  const IconFrown: string
  const IconGift: string
  const IconGitBranch: string
  const IconGitCommit: string
  const IconGitMerge: string
  const IconGitPullRequest: string
  const IconGitHub: string
  const IconGitlab: string
  const IconGlobe: string
  const IconGrid: string
  const IconHardDrive: string
  const IconHash: string
  const IconHeadphones: string
  const IconHeart: string
  const IconHelpCircle: string
  const IconHexagon: string
  const IconHome: string
  const IconImage: string
  const IconInbox: string
  const IconInfo: string
  const IconInstagram: string
  const IconItalic: string
  const IconKey: string
  const IconLayers: string
  const IconLayout: string
  const IconLifeBuoy: string
  const IconLink2: string
  const IconLink: string
  const IconLinkedin: string
  const IconList: string
  const IconLoader: string
  const IconLock: string
  const IconLogIn: string
  const IconLogOut: string
  const IconMail: string
  const IconMapPin: string
  const IconMap: string
  const IconMaximize2: string
  const IconMaximize: string
  const IconMeh: string
  const IconMenu: string
  const IconMessageCircle: string
  const IconMessageSquare: string
  const IconMicOff: string
  const IconMic: string
  const IconMinimize2: string
  const IconMinimize: string
  const IconMinusCircle: string
  const IconMinusSquare: string
  const IconMinus: string
  const IconMonitor: string
  const IconMoon: string
  const IconMoreHorizontal: string
  const IconMoreVertical: string
  const IconMousePointer: string
  const IconMove: string
  const IconMusic: string
  const IconNavigation2: string
  const IconNavigation: string
  const IconOctagon: string
  const IconPackage: string
  const IconPaperclip: string
  const IconPauseCircle: string
  const IconPause: string
  const IconPenTool: string
  const IconPercent: string
  const IconPhoneCall: string
  const IconPhoneForwarded: string
  const IconPhoneIncoming: string
  const IconPhoneMissed: string
  const IconPhoneOff: string
  const IconPhoneOutgoing: string
  const IconPhone: string
  const IconPieChart: string
  const IconPlayCircle: string
  const IconPlay: string
  const IconPlusCircle: string
  const IconPlusSquare: string
  const IconPlus: string
  const IconPocket: string
  const IconPower: string
  const IconPrinter: string
  const IconRadio: string
  const IconRefreshCcw: string
  const IconRefreshCw: string
  const IconRepeat: string
  const IconRewind: string
  const IconRotateCcw: string
  const IconRotateCw: string
  const IconRss: string
  const IconSave: string
  const IconScissors: string
  const IconSearch: string
  const IconSend: string
  const IconServer: string
  const IconSettings: string
  const IconShare2: string
  const IconShare: string
  const IconShieldOff: string
  const IconShield: string
  const IconShoppingBag: string
  const IconShoppingCart: string
  const IconShuffle: string
  const IconSidebar: string
  const IconSkipBack: string
  const IconSkipForward: string
  const IconSlack: string
  const IconSlash: string
  const IconSliders: string
  const IconSmartphone: string
  const IconSmile: string
  const IconSpeaker: string
  const IconSquare: string
  const IconStar: string
  const IconStopCircle: string
  const IconSun: string
  const IconSunrise: string
  const IconSunset: string
  const IconTablet: string
  const IconTag: string
  const IconTarget: string
  const IconTerminal: string
  const IconThermometer: string
  const IconThumbsDown: string
  const IconThumbsUp: string
  const IconToggleLeft: string
  const IconToggleRight: string
  const IconTool: string
  const IconTrash2: string
  const IconTrash: string
  const IconTrello: string
  const IconTrendingDown: string
  const IconTrendingUp: string
  const IconTriangle: string
  const IconTruck: string
  const IconTv: string
  const IconTwitch: string
  const IconTwitter: string
  const IconType: string
  const IconUmbrella: string
  const IconUnderline: string
  const IconUnlock: string
  const IconUploadCloud: string
  const IconUpload: string
  const IconUserCheck: string
  const IconUserMinus: string
  const IconUserPlus: string
  const IconUserX: string
  const IconUser: string
  const IconUsers: string
  const IconVideoOff: string
  const IconVideo: string
  const IconVoicemail: string
  const IconVolume1: string
  const IconVolume2: string
  const IconVolumeX: string
  const IconVolume: string
  const IconWatch: string
  const IconWifiOff: string
  const IconWifi: string
  const IconWind: string
  const IconXCircle: string
  const IconXOctagon: string
  const IconXSquare: string
  const IconX: string
  const IconYoutube: string
  const IconZapOff: string
  const IconZap: string
  const IconZoomIn: string
  const IconZoomOut: string
}
export default _default
