/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { UserCheck } from 'react-feather'

function IconUserCheck(props: any) {
  return <IconBase icon={UserCheck} {...props} />
}

export default IconUserCheck
