/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { PieChart } from 'react-feather'
import IconBase from './../../IconBase'

function IconPieChart(props: any) {
  return <IconBase icon={PieChart} {...props} />
}

export default IconPieChart
