/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { UserMinus } from 'react-feather'

function IconUserMinus(props: any) {
  return <IconBase icon={UserMinus} {...props} />
}

export default IconUserMinus
