/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { CloudRain } from 'react-feather'

function IconCloudRain(props: any) {
  return <IconBase icon={CloudRain} {...props} />
}

export default IconCloudRain
