/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { CloudRain } from 'react-feather'
import IconBase from './../../IconBase'

function IconCloudRain(props: any) {
  return <IconBase icon={CloudRain} {...props} />
}

export default IconCloudRain
