/**
* This file is generated by @wesbitty automatically
* Do Not Edit
*/
declare function IconMoreHorizontal(props: any): import("react/jsx-runtime").JSX.Element;
export default IconMoreHorizontal;
