/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Compass } from 'react-feather'

function IconCompass(props: any) {
  return <IconBase icon={Compass} {...props} />
}

export default IconCompass
