/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Circle } from 'react-feather'
import IconBase from './../../IconBase'

function IconCircle(props: any) {
  return <IconBase icon={Circle} {...props} />
}

export default IconCircle
