/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Volume } from 'react-feather'

function IconVolume(props: any) {
  return <IconBase icon={Volume} {...props} />
}

export default IconVolume
