/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { FastForward } from 'react-feather'

function IconFastForward(props: any) {
  return <IconBase icon={FastForward} {...props} />
}

export default IconFastForward
