/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Box } from 'react-feather'

function IconBox(props: any) {
  return <IconBase icon={Box} {...props} />
}

export default IconBox
