/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Meh } from 'react-feather'

function IconMeh(props: any) {
  return <IconBase icon={Meh} {...props} />
}

export default IconMeh
