/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Mail } from 'react-feather'
import IconBase from './../../IconBase'

function IconMail(props: any) {
  return <IconBase icon={Mail} {...props} />
}

export default IconMail
