/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Layers } from 'react-feather'
import IconBase from './../../IconBase'

function IconLayers(props: any) {
  return <IconBase icon={Layers} {...props} />
}

export default IconLayers
