/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Sunset } from 'react-feather'

function IconSunset(props: any) {
  return <IconBase icon={Sunset} {...props} />
}

export default IconSunset
