// DO NOT EDIT
// This file is generated by IconGenerator script
import React from 'react'
// @ts-ignore
import Icon from 'react-feather/dist/icons/arrow-down-right'
import IconBase from './../../IconBase'

function IconArrowDownRight(props: any) {
  return <IconBase icon={Icon} {...props} />
}

export default IconArrowDownRight
