/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { ArrowDownRight } from 'react-feather'
import IconBase from './../../IconBase'

function IconArrowDownRight(props: any) {
  return <IconBase icon={ArrowDownRight} {...props} />
}

export default IconArrowDownRight
