/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Triangle } from 'react-feather'
import IconBase from './../../IconBase'

function IconTriangle(props: any) {
  return <IconBase icon={Triangle} {...props} />
}

export default IconTriangle
