/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Umbrella } from 'react-feather'
import IconBase from './../../IconBase'

function IconUmbrella(props: any) {
  return <IconBase icon={Umbrella} {...props} />
}

export default IconUmbrella
