/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Image } from 'react-feather'
import IconBase from './../../IconBase'

function IconImage(props: any) {
  return <IconBase icon={Image} {...props} />
}

export default IconImage
