/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Tool } from 'react-feather'
import IconBase from './../../IconBase'

function IconTool(props: any) {
  return <IconBase icon={Tool} {...props} />
}

export default IconTool
