/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { DownloadCloud } from 'react-feather'
import IconBase from './../../IconBase'

function IconDownloadCloud(props: any) {
  return <IconBase icon={DownloadCloud} {...props} />
}

export default IconDownloadCloud
