/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { CornerUpRight } from 'react-feather'

function IconCornerUpRight(props: any) {
  return <IconBase icon={CornerUpRight} {...props} />
}

export default IconCornerUpRight
