/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Cast } from 'react-feather'
import IconBase from './../../IconBase'

function IconCast(props: any) {
  return <IconBase icon={Cast} {...props} />
}

export default IconCast
