/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { Youtube } from 'react-feather'

function IconYoutube(props: any) {
  return <IconBase icon={Youtube} {...props} />
}

export default IconYoutube
