/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { FilePlus } from 'react-feather'

function IconFilePlus(props: any) {
  return <IconBase icon={FilePlus} {...props} />
}

export default IconFilePlus
