/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { FileMinus } from 'react-feather'

function IconFileMinus(props: any) {
  return <IconBase icon={FileMinus} {...props} />
}

export default IconFileMinus
