name: Check

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

permissions:
  contents: read

jobs:
  prettier-check:
    permissions:
      actions: read
      contents: read
      security-events: write
    name: Check Code - Prettier
    strategy:
      matrix:
        node-version: [16]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: check code
        run: |
          npx prettier --check .

  types-check:
    name: Types check - UI
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: check types
        run: |
          npm run types-check
        working-directory: packages/ui
