name: Chromatic

on:
  push:
    branches:
      - 'patches/sort'
  pull_request:
    branches:
      - 'patches/sort'

jobs:
  ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 16.17.1
        uses: actions/setup-node@v3
        with:
          node-version: 16.17.1
      - name: Build
        run: |
          npm install
          npm run build
        working-directory: packages/ui
      - name: Deploy
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          storybookBuildDir: packages/ui/storybook-static
