name: 'Chromatic'
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 16.17.1
        uses: actions/setup-node@v3
        with:
          node-version: 16.17.1
      - run: npm install
      - run: npm run build
      - run: npm run build-storybook
        working-directory: packages/ui
      - uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          storybookBuildDir: packages/ui/storybook-static
