name: Check & Format Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-code:
    name: Check Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Check Prettier
        run: npx prettier --check .
