name: Format

on:
  push:
    branches: ['changelog']
  pull_request:
    branches: ['main']

jobs:
  format:
    strategy:
      matrix:
        node-version: [16]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run prettier
