name: Release

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  release-ui:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v2

      - name: Prepare Repo
        run: git fetch --unshallow --tags

      - name: Use Node.js 16.17.1
        uses: actions/setup-node@v3
        with:
          node-version: 16.17.1

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run release
        working-directory: packages/ui
