/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { Trello } from 'react-feather'
import IconBase from './../../IconBase'

function IconTrello(props: any) {
  return <IconBase icon={Trello} {...props} />
}

export default IconTrello
