/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { ChevronLeft } from 'react-feather'
import IconBase from './../../IconBase'

function IconChevronLeft(props: any) {
  return <IconBase icon={ChevronLeft} {...props} />
}

export default IconChevronLeft
