/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { ChevronLeft } from 'react-feather'

function IconChevronLeft(props: any) {
  return <IconBase icon={ChevronLeft} {...props} />
}

export default IconChevronLeft
