/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import IconBase from './../../IconBase'
import * as React from 'react'
// @ts-ignore
import { CornerLeftDown } from 'react-feather'

function IconCornerLeftDown(props: any) {
  return <IconBase icon={CornerLeftDown} {...props} />
}

export default IconCornerLeftDown
