/**
 * This file is generated by @wesbitty automatically
 * Do Not Edit
 */

import * as React from 'react'
// @ts-ignore
import { MessageCircle } from 'react-feather'
import IconBase from './../../IconBase'

function IconMessageCircle(props: any) {
  return <IconBase icon={MessageCircle} {...props} />
}

export default IconMessageCircle
